#!/bin/sh
### BEGIN INIT INFO
# Provides:          firebot
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: firebot, the irc.mozilla.org irc bot
# Description:       firebot, irc bot for irc.mozilla.org
### END INIT INFO

case "$1" in
    start)
        echo -n "Starting firebot "
        su -c /home/firebot/firebot/start firebot
        pidof -x mozbot.pl
        ;;
    stop)
        echo "Shutting down firebot "
        su -c /home/firebot/firebot/stop firebot
        sleep 10
        killall -u firebot
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    reload)
        echo -n "Reloading configuration "
        su -c /home/firebot/firebot/reload firebot
        ;;
    status)
        /home/firebot/firebot/status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
        ;;
esac
exit 0
