#!/bin/sh
### BEGIN INIT INFO
# Provides:          firebot
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: firebot, the irc.mozilla.org irc bot
# Description:       firebot, irc bot for irc.mozilla.org
### END INIT INFO

pushd `dirname $0`/.. >/dev/null
BOT_PATH=`pwd`

case "$1" in
    start)
        echo -n "Starting firebot "
        su -c "$BOT_PATH/scripts/start" firebot
        pidof -x mozbot.pl
        ;;
    stop)
        echo "Shutting down firebot "
        su -c "$BOT_PATH/scripts/stop" firebot
        sleep 10
        killall -u firebot
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    reload)
        echo -n "Reloading configuration "
        su -c "$BOT_PATH/scripts/reload" firebot
        ;;
    status)
        "$BOT_PATH/scripts/status"
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
        ;;
esac
exit 0
