#!/bin/sh
pushd `dirname $0`/.. >/dev/null
P=`/sbin/pidof -x mozbot.pl`
if [ -n "$P" ]; then
    if [ "$1" != "-q" ]; then
        echo firebot is already running
        /usr/bin/pstree -p "$P"
    fi
else
    echo starting firebot
    >nohup.out
    /usr/bin/nohup ./mozbot.pl &
fi
