D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < airport.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < areacodes.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < country_net_codes.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < dos.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < html.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < jargon-split.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < jargon.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < linux-howto.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < Linux.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < LinuxFS.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < MacErrorCodes.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < Mac_Atrap_Calls.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < old_test_meanings.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < peri_abb_and_num.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < ports.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < pTkfunc.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < rfc_index.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < rx_codes.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < security.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < techdict.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < UnixCmds.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < usazips.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < weather.fact
D:\mozbot\BotModules\Infobot.pl -i ../factoids-is < weather2.fact
